UDP + NONBLOCK

diff --git a/tests/test-run-all b/tests/test-run-all
--- a/tests/test-run-all
+++ b/tests/test-run-all
@@ -5,23 +5,34 @@ set -eu
 source "utils/common"
 
 function teardown {
-    kill "$stackip"
+    stackip=$(pidof lvl-ip) || true
+    [[ $stackip ]] && kill "$stackip"
 }
 
 trap teardown EXIT ERR
+# trap teardown EXIT
 
 start_stack
-echo "Started lvl-ip with pid $stackip"
-sleep 5 # wait for stack to establish itself
+echo "Started lvl-ip, wait for stack to establish itself" && sleep 5
 
+lvl_ip_check
 pids=""
 
 tc qdisc add dev tap0 root handle 1: htb
 
-./suites/arp/suite-arp &
+# udp 测试 START
+./suites/udp/suite-udp &
 pids="$pids $!"
-./suites/icmp/suite-icmp &
-pids="$pids $!"
+# udp 测试 END
+# !!! 这里不能直接exit, 否则会导致lvl-ip进程退出
+# !!! 这里不能直接exit, 否则会导致lvl-ip进程退出
+# !!! 这里不能直接exit, 否则会导致lvl-ip进程退出
+
+# ./suites/arp/suite-arp &
+# pids="$pids $!"
+# ./suites/icmp/suite-icmp &
+# pids="$pids $!"
+
 ./suites/tcp/suite-curl &
 pids="$pids $!"
 ./suites/tcp/suite-packet-delay &
@@ -38,7 +49,7 @@ for i in $pids; do
   [ "$pid_rc" -ne 0 ] && rc="$pid_rc"
 done
 
-grep -i -B50 "SUMMARY: ThreadSanitizer:" ../lvl-ip-test.log && echo "Possible threading errors found."
+grep -iq "SUMMARY: ThreadSanitizer:|SUMMARY: AddressSanitizer:" $repo/logs/stdprint.log && echo -e "Possible a/tsan errors found."
 
 echo
 [ "$rc" -eq 0 ] && echo "Tests pass."
